---
version: "3.0"

services:

  varnish:
    image: ivancollg/varnish_v6
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  apache:
    image: ivancollg/apache2_v6
    volumes:
      - "apache-fpm:/var/www"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  phpfpm:
    image: ivancollg/phpfpm8.1_v1
    volumes:
      - "apache-fpm:/var/www"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  memcached:
    image: ivancollg/memcached_v2
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  mariadb:
    image: ivancollg/mariadb_v1
    volumes:
      - "db-data:/var/lib/mysql"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DB_SERVICE_NAME=galera
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupaldb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
  phpmyadmin:
    image: ivancollg/phpmyadmin_v1
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8081:80"
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  apache-fpm:
    driver: local
    driver_opts:
     o: bind
     type: none
     device: /mnt/apache-data
  db-data:
    driver: local
    driver_opts:
     o: bind
     type: none
     device: /mnt/data
...


