#! /bin/bash

#Download CMS Drupal 8
if [ ! -d /var/www/drupal ]
then
	wget -q https://ftp.drupal.org/files/projects/drupal-10.0.8.tar.gz && \
	tar -zxf drupal-10.0.8.tar.gz && \
	mv drupal-10.0.8 /var/www/drupal && \
	rm tar.gz && \
	chown -R www-data:www-data /var/www/drupal
fi
	

#Change port
sed -i "s/80/8080/g" /etc/apache2/ports.conf

#Start apache proccess
killall apache2
apache2ctl -D FOREGROUND

